### ISSUE TITLE
Multilingual preprocessing

### ISSUE THREAD

**Issue by sshleifer** [Helsinki-NLP/OPUS-MT-train#10]
For this multilingual model (en-ROMANCE), [test set](https://object.pouta.csc.fi/OPUS-MT-models/en-fr+fr_BE+fr_CA+fr_FR+wa+frp+oc+ca+rm+lld+fur+lij+lmo+es+es_AR+es_CL+es_CO+es_CR+es_DO+es_EC+es_ES+es_GT+es_HN+es_MX+es_NI+es_PA+es_PE+es_PR+es_SV+es_UY+es_VE+pt+pt_br+pt_BR+pt_PT+gl+lad+an+mwl+it+it_IT+co+nap+scn+vec+sc+ro+la/opus-2020-04-21.test.txt)
I am having trouble running inputs with language codes through marian.
Specifically, if I add the codes after running `spm_encode`, things are fine.
If I try to use the preprocessing logic in `preprocess.sh`, things break.

test set: `>>pt<< Don't spend so much time watching TV.`

Using preprocess.sh, I get either
```bash
▁> > pt < < ▁Don ' t ▁spend ▁so ▁much ▁time ▁watching ▁TV .
```
or
```
>>pt<< ▁> > pt < < ▁Don ' t ▁spend ▁so ▁much ▁time ▁watching ▁TV .
```
but both of those cause marian_decoder to error.

The correct input seems to be 
```bash
>>pt<< ▁Don ' t ▁spend ▁so ▁much ▁time ▁watching ▁TV .
```
With the code added after `spm_encode` is run. Is that correct?

**Comment by jorgtied** [comment]
Yes, the last line is correct. You should preprocess.sh without the language flag. That will be added after tokenisation - so yes, it should come after spm-encode. preprocess.sh should work if you have plain text as input without the language token. Does that work?

**Comment by sshleifer** [comment]
Yes, thanks!
