### ISSUE TITLE
Training dataset statistics or technical reports

### ISSUE THREAD

**Issue by phphuc612** [Helsinki-NLP/OPUS-MT-train#103]
Thanks for your all great work!

I'm currently in search of any technical reports or training data statistics as a reference for your work. If such resources are available, could you please share relevant information?

Thank you in advance!

**Comment by jorgtied** [comment]
For the Tatoeba models you would have information about the training data here: https://github.com/Helsinki-NLP/Tatoeba-Challenge/. The model cards / README files will also give you some statistics that could help. Unfortunately, there is no comprehensive technical report that includes all details for all models. Apologies for that.
