### ISSUE TITLE
Are the models released under MIT License?

### ISSUE THREAD

**Issue by alexcombessie** [Helsinki-NLP/OPUS-MT-train#12]
Hi,

Thank you for releasing this. Very very interesting work. I plan to test this in the coming months.

Can you confirm that the pretrained models you distribute on this repo and through [huggingface](https://huggingface.co/Helsinki-NLP) are under MIT License?

Thank you,

Alex

**Comment by jorgtied** [comment]
The models are distributed with CC-BY 4.0. I added a note. Sorry for the confusion.

**Comment by alexcombessie** [comment]
Thanks for confirming, and thanks again for this work. Have a good weekend!
