### ISSUE TITLE
Chinese-English model?

### ISSUE THREAD

**Issue by ales-t** [Helsinki-NLP/OPUS-MT-train#13]
Thank you for this great resource, it's a really impressive collection of models.

I've noticed there are models for zh->fi, zh->sv and zh->de but no model for zh->en (or en->zh for that matter). Since these are quite prominent language pairs, I'm wondering if there are plans to add these in the future? Or am I just looking wrong?

**Comment by jorgtied** [comment]
Those models crashed and we still need to figure out why. Hopefully, more models including zh-en will arrive soon. Apologies for the inconvenience ....

**Comment by YosuaMichael** [comment]
Hi, is it possible to get the old model for zh -> en ?

**Comment by jorgtied** [comment]
Finally, there are now models for Chinese to English and vice versa: Check
https://github.com/Helsinki-NLP/Tatoeba-Challenge/tree/master/models/zho-eng
https://github.com/Helsinki-NLP/Tatoeba-Challenge/tree/master/models/eng-zho

**Comment by ales-t** [comment]
@jorgtied Great, thank you! In that case, I would propose to close the issue as resolved. I'm not sure what's the policy of this project, can I do it or should it be done by one of the maintainers?

**Comment by jingmouren** [comment]
how to load that 'Tatoeba-Challenge//zho-eng' model?
