### ISSUE TITLE
en-es / es-en : spm instead of bpe?

### ISSUE THREAD

**Issue by pentegroom** [Helsinki-NLP/OPUS-MT-train#16]
Hi, 

Do you have spm versions of the tokenization for es-en / en-es models since source and target spm are required to convert to models into pytorch? 

Thank you.

**Comment by jorgtied** [comment]
Unfortunately, I don't have any sentencepiece model at this moment but more models will come and soon be released. Most of them will appear from this repository: https://github.com/Helsinki-NLP/Tatoeba-Challenge

**Comment by pentegroom** [comment]
thank you so much.

**Comment by jorgtied** [comment]
There is now https://github.com/Helsinki-NLP/Tatoeba-Challenge/tree/master/models/eng-spa and https://github.com/Helsinki-NLP/Tatoeba-Challenge/tree/master/models/spa-eng

**Comment by pentegroom** [comment]
Thank you so much.
