### ISSUE TITLE
Request for EN-PL model

### ISSUE THREAD

**Issue by djstrong** [Helsinki-NLP/OPUS-MT-train#46]
It would be great to see EN-PL model!

**Comment by jorgtied** [comment]
It will come soon I hope.

**Comment by jorgtied** [comment]
Did you notice that we now have https://github.com/Helsinki-NLP/Tatoeba-Challenge/tree/master/models/eng-pol?

**Comment by djstrong** [comment]
Oh, thank you!

**Comment by djstrong** [comment]
I guess it is time consuming to upload all models to huggingface hub, but it would be helpful.

**Comment by djstrong** [comment]
@jorgtied I am trying to run this model with command: `/build/marian-decoder -c eng-pol/opus-2021-02-19/decoder.yml` but the translation is much worse than in `opus-2021-02-19.test.txt`. What am I missing?

**Comment by jorgtied** [comment]
Did you preprocess the input data with the subword segmentation model? You need to do that before piping it in into the decoder. See the preprocess script that comes with the model release.

**Comment by Konskow** [comment]
Has anyone had any luck with converting the model to pytorch? I tried:
```
python src/transformers/models/marian/convert_marian_tatoeba_to_pytorch.py  --models eng-pol --save_dir converted
```
It successfully creates a converted model but unfortunately, it doesn't work. I get empty strings as a result.
