### ISSUE TITLE
models/ru-fr/README.md

### ISSUE THREAD

**Issue by sshleifer** [Helsinki-NLP/OPUS-MT-train#6]
Two models added in separate commit with same filenames. 

[readme](https://github.com/Helsinki-NLP/OPUS-MT-train/blame/master/models/ru-fr/README.md)
Are these russian characters? (from https://object.pouta.csc.fi/OPUS-MT-models/ru-fr/opus-2020-01-16.test.txt).

```bash
src: Ð¯ Ð½Ðµ Ð¿Ð¾Ð½Ð¸Ð¼Ð°ÑŽ, Ñ‡Ñ‚Ð¾ ÑÑ‚Ð¾ Ð·Ð½Ð°Ñ‡Ð¸Ñ‚.
system: Je ne comprend pas ce que cela signifie.
gold: Je ne comprends pas ce que Ã§a veut dire.
```

**Comment by jorgtied** [comment]
Web browsers don't seem to have utf-8 as default. It should be fine if you change the text encoding. Unfortunately, I cannot change default char-sets in the objectstorage URL.

**Comment by sshleifer** [comment]
Resolved. if you  
```bash
curl object.pouta.csc.fi/OPUS-MT-models/ru-fr/opus-2020-01-16.test.txt
``` 
It looks nice.
