### ISSUE TITLE
Problem Fine-tuning Models using TMX files

### ISSUE THREAD

**Issue by hdeval1** [Helsinki-NLP/OPUS-MT-train#67]
Hi! 
I have been working with the opus-mt models available through HuggingFace and was hoping to finetune them using TMX files. At this point, I have been able to install the listed prerequisites and follow the documentation but the tmx-tune recipe is failing. It is failing around the ${TUNED_MODEL}.done target starting around line 520. The LOADMODS environment variable is empty which is causing the failure. The repo contains no documentation mentioning the value of LOADMODS and it is not being set anywhere so I am lost on what it should be. 

More information (not sure if this is related/helpful to answer the question):
- I have created a Docker container to set up this environment that uses a CUDA based Ubuntu image and currently I am not using GPU for testing but I do have access to one if needed
- To get to this point, I have had to move files/directories around (i.e moving the tools directory from OPUS-MT-train to OPUS-MT-train/finetune and run the Makefile from that directory) 
- I have tried arbitrarily setting LOADMODS in the make tmx-tune command and the recipe still fails on the ${TUNED_MODEL}.done target because ${TRAIN_SRC}.pre.gz is empty

**Comment by jorgtied** [comment]
Ah, sorry - I changed that variable name to LOAD_ENV. Could you replace LOADMODS with LOAD_ENV and try again?

**Comment by hdeval1** [comment]
Hi! Thank you for the response. I changed the LOADMODS variable to LOAD_ENV and tried again. LOAD_ENV is being set to echo "nothing to load". When I ran the make tmx-tune command again, the recipe still fails on the ${TUNED_MODEL}.done target because ${TRAIN_SRC}.pre.gz is empty. The logs say that it is aborting from marian::data::CorpusBase (corpus_base.cpp line 349) if that helps.  I assume all of the *.pre.gz files are empty. The ${TRAIN_SRC} and {TRAIN_TRG} files are also empty.

**Comment by jorgtied** [comment]
Could you try to remove those empty files and start again? It might be some orphaned files from your previous attempt that block the system.

**Comment by hdeval1** [comment]
I removed the entire directory it created (i.e. en-fr) but unfortunately I am still getting that same error that ${TRAIN_SRC}.pre.gz is empty causing the recipe to fail.

**Comment by hdeval1** [comment]
So I was able to get past this by building my own model with the tatoeba-prepare and train recipes! Now just working through changing some of the values, thank you for your help!
