### ISSUE TITLE
[ga-en] Broken Link to test.txt

### ISSUE THREAD

**Issue by sshleifer** [Helsinki-NLP/OPUS-MT-train#8]
This [link](https://object.pouta.csc.fi/OPUS-MT-models/ga+cy+br+gd+kw+gv-en/opus+techiaith+bt-2020-04-30.test.txt),  from this [README](https://github.com/Helsinki-NLP/OPUS-MT-train/blob/master/models/ga+cy+br+gd+kw+gv-en/README.md), seems broken.
Do you still have the file to repost?
Thanks!

**Comment by jorgtied** [comment]
fixed with a new model upload and updated README
